### ISSUE TITLE
Add documentation to build on x86/x64

### ISSUE THREAD

**Issue by atom2626** [AtlantsEmbedded/IntelliPi#14]
Add a wiki section with the instructions to build braintone on a x86/x64 platform. This involves cloning the git (data_interface, data_preprocessing, braintone_app), cloning the stub files and copying them into place, editing the makefile, building and launching the apps.

**Comment by zimbob10k** [comment]
I think this can be achieved via defines.

  Gpio interface used to be fine without stubs because the preprocessor will not see the undefined symbols or dependencies.

**Comment by atom2626** [comment]
i want to write a wiki page describing the process. your comment is pertinent though, there is a way to manage this through defines.

---

De : ronniebrash notifications@github.com
Envoyé : 2 février 2016 09:41:35
À : AtlantsEmbedded/IntelliPi
Cc : atom2626
Objet : Re: [IntelliPi] Add documentation to build on x86/x64 (#14)

I think this can be achieved via defines.

Gpio interface used to be fine without stubs because the preprocessor will not see the undefined symbols or dependencies.

##

**Comment by Knight1990** [comment]
don't work for raspberry pi v2 B+! please help me

**Comment by zimbob10k** [comment]
Knight1990,  please add to the other ticket https://github.com/AtlantsEmbedded/IntelliPi/issues/18

**Comment by atom2626** [comment]
x86/x64 are now supported through the script and documentation is in the wiki.

Raspbian remain to be validated
