### ISSUE TITLE
Getting started guide incomplete

### ISSUE THREAD

**Issue by gabriel-amyot** [AtlantsEmbedded/IntelliPi#16]
At  [checkout intelliroot step](https://github.com/AtlantsEmbedded/IntelliPi/wiki/Complete-guide-to-getting-started-with-the-Intellipi#checkout-intelliroot), the checkout of the configurations are missing.  I had to use the configurations from [AtomEmbedded Machine Learning Products](https://sourceforge.net/p/atomproducts/documentation/Getting%20started/)'s guide.

**Comment by zimbob10k** [comment]
Are you absolutely sure? As per the documentation and github structure:

> git clone https://github.com/AtlantsEmbedded/IntelliPi.git intelli_git
> cd intelli_git/intelliroot
> 
> The buildroot is downloaded, but the default package and software configurations to be used by the build process need to be specified.
> 
> cp ../configs/Dev-fullenv .config

After cloning our github with the above command, inside of the intelli_git folder, you will have two folders {configs and intelliroot] and the README.  If you cd as per the command and then run the cp command, the step you are referring to from the legacy documentation is not required.

**Comment by gabriel-amyot** [comment]
You are right, I missed it.
Sorry about that
