### ISSUE TITLE
Compilation failed due to file download.

### ISSUE THREAD

**Issue by MoistBit** [AtlantsEmbedded/IntelliPi#22]
Hello, I am trying to run make after all steps have been followed. I have ran into the file named 9d268f00de7c13afa315fe2d303265d535c4bdf0.tar.gz and cannot find a download page for it. 

`HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/Hexxeh/rpi-firmware/tar.gz/9d268f00de7c13afa315fe2d303265d535c4bdf0 [following]
--2020-06-19 05:09:43--  https://codeload.github.com/Hexxeh/rpi-firmware/tar.gz/9d268f00de7c13afa315fe2d303265d535c4bdf0
Resolving codeload.github.com (codeload.github.com)... 140.82.114.9
Connecting to codeload.github.com (codeload.github.com)|140.82.114.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: 'STDOUT'

-                                           [                        <=>                                                   ]  48.24M   723KB/s    in 69s     

2020-06-19 05:10:53 (717 KB/s) - written to stdout [50578847]

MD5 sum of the downloaded file does not match (file: 3dc22a9e627e40235c0970bf23ba6a85, requested: 21ac2ba64ef045655b4d4677b3fdf6cd) - deleting download.
--2020-06-19 05:10:53--  http://mirror2.openwrt.org/sources/9d268f00de7c13afa315fe2d303265d535c4bdf0.tar.gz
Resolving mirror2.openwrt.org (mirror2.openwrt.org)... 46.4.11.11, 2a01:4f8:221:3d45::2
Connecting to mirror2.openwrt.org (mirror2.openwrt.org)|46.4.11.11|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-19 05:10:53 ERROR 404: Not Found.

Download failed.
--2020-06-19 05:10:53--  http://downloads.openwrt.org/sources/9d268f00de7c13afa315fe2d303265d535c4bdf0.tar.gz
Resolving downloads.openwrt.org (downloads.openwrt.org)... 176.9.48.73, 2a01:4f8:150:6449::2
Connecting to downloads.openwrt.org (downloads.openwrt.org)|176.9.48.73|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.openwrt.org/sources/9d268f00de7c13afa315fe2d303265d535c4bdf0.tar.gz [following]
--2020-06-19 05:10:53--  https://downloads.openwrt.org/sources/9d268f00de7c13afa315fe2d303265d535c4bdf0.tar.gz
Connecting to downloads.openwrt.org (downloads.openwrt.org)|176.9.48.73|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.openwrt.org/9d268f00de7c13afa315fe2d303265d535c4bdf0.tar.gz [following]
--2020-06-19 05:10:54--  https://sources.openwrt.org/9d268f00de7c13afa315fe2d303265d535c4bdf0.tar.gz
Resolving sources.openwrt.org (sources.openwrt.org)... 148.251.151.136, 2a01:4f8:210:5087::2
Connecting to sources.openwrt.org (sources.openwrt.org)|148.251.151.136|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-19 05:10:54 ERROR 404: Not Found.

Download failed.
No more mirrors to try - giving up.
Makefile:43: recipe for target '/home/f4/intelli_git/intelliroot/dl/9d268f00de7c13afa315fe2d303265d535c4bdf0.tar.gz' failed
make[3]: *** [/home/f4/intelli_git/intelliroot/dl/9d268f00de7c13afa315fe2d303265d535c4bdf0.tar.gz] Error 2
make[3]: Leaving directory '/home/f4/intelli_git/intelliroot/package/kernel/brcm2708-gpu-fw'
package/Makefile:173: recipe for target 'package/kernel/brcm2708-gpu-fw/compile' failed
make[2]: *** [package/kernel/brcm2708-gpu-fw/compile] Error 2
make[2]: Leaving directory '/home/f4/intelli_git/intelliroot'
package/Makefile:170: recipe for target '/home/f4/intelli_git/intelliroot/staging_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/stamp/.package_compile' failed
make[1]: *** [/home/f4/intelli_git/intelliroot/staging_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/f4/intelli_git/intelliroot'
/home/f4/intelli_git/intelliroot/include/toplevel.mk:171: recipe for target 'world' failed
make: *** [world] Error 2
`

**Comment by atom2626** [comment]
Hey,

I wish I could help you, but I discontinued the support on this project a while ago.

If you are interested, in a professional way, my new business https://www.re-ak.com/ offers a multi-modal kit that pushed the Intellipi to a whole new level.

________________________________

**Comment by fadedreamz** [comment]
@MoistBit modify the script and try with similar tar.gz files from https://sources.openwrt.org/
Not guaranteed to work, but it will work if the older tar.gz is compatible with the missing one.

**Comment by MoistBit** [comment]
Hello, I have found one that worked. Some reason when copy and pasting the
link from the terminal the download file is available. I am having trouble
running it on a raspberry pi 3b+ by the way. I do not own an original Pi. I
will see if i can tweak the kernel or menuconfig to see if i can get it to
boot.
